spring.application.name=Back

# Mantendo as credenciais que funcionaram!
spring.datasource.url=jdbc:firebirdsql://localhost:3050/C:/Users/joaop/Documents/OrionERP/DADOS.FDB?charSet=UTF-8
spring.datasource.username=SYSDBA
spring.datasource.password=1811
spring.datasource.driver-class-name=org.firebirdsql.jdbc.FBDriver

# REMOVA OU COMENTE A LINHA DO DIALETO ANTIGO (O Hibernate 6 detecta sozinho)
# spring.jpa.database-platform=org.hibernate.dialect.FirebirdDialect

# Se o Hibernate reclamar da falta de dialeto, use esta linha da comunidade abaixo:
spring.jpa.database-platform=org.hibernate.community.dialect.FirebirdDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB